apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "gb.fullname" . }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
  - hosts:
    - {{ .Values.hostUrl }}
    secretName: gb-cert
  rules:
  - host: {{ .Values.hostUrl }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "gb.fullname" . }}
          servicePort: 80

