## Gate
##

image: jkaberg/weechat
imagePullPolicy: Always
hostUrl: weechat-gateway.example.com

ingress:
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
persistence:
  enabled: true
  #existingClaim: weechat
  skipuninstall: true
  accessMode: ReadWriteOnce
  size: 2Gi
  # storageClass: hdd

resources:
  requests:
    memory: 256Mi
    cpu: 100m

